# Generated by Django 3.2.12 on 2022-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comments',
            name='foodname',
            field=models.CharField(default='', max_length=30, verbose_name='username'),
        ),
    ]
