# Generated by Django 3.2 on 2022-04-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('foodID', models.IntegerField(primary_key=True, serialize=False, verbose_name='foodID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='stars')),
            ],
        ),
    ]
