# Generated by Django 3.2 on 2022-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='stars'),
        ),
    ]
