# Generated by Django 3.2 on 2022-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='spiciness',
            field=models.IntegerField(default=0, verbose_name='spiciness'),
        ),
    ]
