# Generated by Django 3.2 on 2022-05-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_spiciness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='spiciness',
            field=models.IntegerField(default=1, verbose_name='spiciness'),
        ),
    ]
