# Generated by Django 3.2.12 on 2022-05-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_name'),
        ('food', '0005_alter_food_name'),
    ]

    operations = [
    ]
