# Generated by Django 3.2 on 2022-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='unlikes',
            field=models.IntegerField(default=0, verbose_name='Unlikes'),
        ),
    ]
